# Generated by Django 3.2.13 on 2023-08-26 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FavoriteRecipes',
                'verbose_name_plural': 'FavoriteRecipes',
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the Ingredient', max_length=200, verbose_name='Ingridient Name')),
                ('measurement_unit', models.CharField(help_text='Unit to measure the Ingredient', max_length=20, verbose_name='Measurement unit')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientsForRecipeInAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Write the required Amount of this Ingredient', verbose_name='Amount of the Ingredient')),
            ],
            options={
                'verbose_name': 'IngredientRecipe',
                'verbose_name_plural': 'IngredientsRecipe',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title for the Recipe Publishing', max_length=200, verbose_name='Title of the recipe')),
                ('text', models.TextField(help_text='Text to describe the Recipe', verbose_name='Description of the recipe')),
                ('image', models.ImageField(help_text='Image to illustrate the Recipe', upload_to='recipes/images', verbose_name='Image of the recipe')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Coocking time (in minutes)', validators=[django.core.validators.MinValueValidator(1, 'Cooking time is at least 1 minute, if you just read :).')], verbose_name='Coocking time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication day')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title for Tag', max_length=200, verbose_name='Tag Name')),
                ('color', models.CharField(help_text='Hex-code for color, for example: #FF0000', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='The entered value is not a color in the format HEX!', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Hex-code')),
                ('slug', models.SlugField(help_text='Title for Slug', unique=True, verbose_name='Slug id')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_list', to='recipes.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Shopping list',
                'verbose_name_plural': 'Shopping lists',
            },
        ),
    ]
