# Generated by Django 3.2.13 on 2023-08-23 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230823_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Hex-code for color, for example: #FF0000', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='The entered value is not a color in the format HEX!', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Hex-code'),
        ),
    ]
